resource_group_name     = "exampleResourceGroup"
storage_account_name    = "examplestoraccount"
location                = "UK South"  
account_tier            = "Standard"  
account_replication_type = "GRS"      
